#!/bin/sh

CWD=$(pwd)

# zsh
echo " Linking zsh"
ln -s $CWD/zsh ~/.zsh
ln -s $CWD/zsh/zshrc ~/.zshrc

# nvim
echo " Adding plugins"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo " Linking neovim"
mkdir ~/.config/nvim
ln -s $CWD/vimrc ~/.config/nvim/init.vim
mkdir ~/.local/share/nvim/undo

# tmux
echo " Linking tmux"
ln -s $CWD/tmux.conf ~/.tmux.conf
