#!/bin/sh

CWD=$(pwd)

# homebrew
if test ! $(which brew)
then
    echo " Installing Homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew install git coreutils zsh neovim/neovim/neovim nginx

# zsh
echo " Linking zsh"
ln -s $CWD/zsh ~/.zsh
ln -s $CWD/zsh/zshrc ~/.zshrc

# nvim
echo " Adding plugins"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo " Linking neovim"
ln -s $CWD/vimrc ~/.config/nvim/init.vim
ln -s $CWD/filetype ~/.config/nvim/ftdetect
mkdir ~/.local/share/nvim/undo

# i3wm
echo " Linking i3wm"
ln -s $CWD/i3 ~/.config/i3
ln -s $CWD/i3/i3status.conf ~/.i3status.conf
