#!/bin/sh

CWD=$(pwd)
OS=$(uname)

# Linux or mac
if [ "${OS}" = "Linux" ]
then
	echo " Doing nothing"
else
	# homebrew
	if test ! $(which brew)
	then
	    echo " Installing Homebrew"
	    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi

	brew install git coreutils zsh neovim/neovim/neovim nginx
fi

# zsh
echo " Linking zsh"
ln -s $CWD/zsh ~/.zsh
ln -s $CWD/zsh/zshrc ~/.zshrc

# nvim
echo " Adding plugins"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo " Linking neovim"
ln -s $CWD/vim/vimrc ~/.config/nvim/init.vim
mkdir ~/.local/share/nvim/undo

# tmux
echo " Linking tmux"
ln -s $CWD/tmux ~/.tmux
ln -s $CWD/tmux/tmux.conf ~/.tmux.conf
