" plugins
call plug#begin('~/.local/share/nvim/plugged')

Plug 'scrooloose/NERDTree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'airblade/vim-gitgutter'
Plug 'mhartington/oceanic-next'
Plug 'tpope/vim-sleuth'
Plug 'junegunn/goyo.vim'
Plug 'pangloss/vim-javascript'
Plug 'terryma/vim-multiple-cursors'

call plug#end()

" nerdtree
" autocmd vimenter * NERDTree
map <C-n> :NERDTreeToggle<CR>
let NERDTreeIgnore = ['\.rej$']

" gutter
set number
set relativenumber
let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '◆'
let g:gitgutter_sign_removed = '-'
let g:gitgutter_sign_removed_first_line = '^'
let g:gitgutter_sign_modified_removed = '~'

" ui
set cursorline
set showcmd

if (has("termguicolors"))
	set termguicolors
endif

" theme
syntax enable
colorscheme OceanicNext

" indent
set autoindent

" trailing
autocmd BufWritePre * %s/\s\+$//e

" airline
let g:airline_theme='oceanicnext'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

" no arrow
" http://jeetworks.org/vim-making-those-arrow-keys-work-for-you-or-why-the-anti-arrow-key-propoganda-is-wrong/
noremap		<Up>	<NOP>
noremap		<Down>	<NOP>
noremap		<Left>	<NOP>
noremap		<Right>	<NOP>
inoremap	<Up>	<NOP>
inoremap	<Down>	<NOP>
inoremap	<Left>	<NOP>
inoremap	<Right>	<NOP>

" big jump with J and K
nnoremap	J	15j
nnoremap	K	15k
vnoremap	J	15j
vnoremap	K	15k

" js
let g:javascript_plugin_jsdoc = 1

" buffers
nnoremap 	<c-h>	:bp<CR>
nnoremap	<c-l>	:bn<CR>

" ctrlp
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlPMixed'
let g:ctrlp_custom_ignore = {
	\ 'dir': 'node_modules'
	\ }

" multiple-cursors (sublime like)
let g:multi_cursor_next_key = '<c-d>'
let g:multi_cursor_prev_key = '<c-s>'
