set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle
call vundle#begin()

" automatically manage vundle
Plugin 'VundleVim/Vundle.vim'

" UI
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()
filetype plugin indent on

" basics
syntax on
set number
set cursorline
set showcmd
set mouse=a

set autoindent
set tabstop=4
set shiftwidth=4
set softtabstop=4

" colors
set background=dark
colorscheme hybrid

" swap
set directory=$HOME/.vim_tmp/

" NERDTree
" automatically start if no file specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" open it on ctrl + n
map <C-n> :NERDTreeToggle<CR>
" close it if closing the last file
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" airline
let g:airline_powerline_fonts = 1
" enable smart tabs
let g:airline#extensions#tabline#enabled = 1

" git
let g:gitgutter_enabled = 1
