#!/usr/bin/env zsh

#  _____________ __  __ _____   _____ 
#  |___   |   __| |  | |  __ \ / ____|
#     /  /|  |__| |__| | |__) | |     
#    /  / |__   |  __  |  _  /| |     
# _ /  /__ __|  | |  | | | \ \| |____ 
#(_)______|_____|_|  |_|_|  \_\\_____|
#

# PATH
export PATH=/usr/sbin:/usr/local/bin:/usr/local/Cellar:$HOME/bin:$HOME//Library/Haskell/ghc-7.6.3/lib/cabal-install-1.18.0.3/bin:/sbin:/opt/local/bin:/opt/local/sbin:$PATH

# Colors
eval `gdircolors $HOME/.zsh/colors`
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Differents files to source
for file in $HOME/.zsh/*.zsh; do
	source $file
done

# History
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
HISTFILE=~/.zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export HISTFILE HISTSIZE SAVEHIST
setopt histverify

export PANDOREHOME=/usr/sbin/pandore
export PATH=/usr/sbin/pandore:/usr/sbin/pandore/bin:$PATH
export LD_LIBRARY_PATH=/usr/sbin/pandore/lib:$LD_LIBRARY_PATH

local os host

# Set default umask to 557
umask 022

export NVM_DIR="/Users/zarov/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
